# **Synthetic Dataset for Risk Assessment and Loan Approval Modeling**
This synthetic dataset comprises 20,000 records of personal and financial data, designed to facilitate the development of predictive models for risk assessment. 

## Problem Statement

**A bank aims to develop a data-driven credit risk assessment system to improve the loan approval process and minimize the risk of loan defaults.** The bank has provided a dataset containing applicants’ demographic, employment, income, credit history, existing debt, and other financial information.

The objective of this project is to analyze these factors and develop **machine learning models for two key banking tasks**:

1. **Risk Score Prediction (Regression):** Predict a continuous risk score for each loan applicant to assess their likelihood of financial instability or loan default.
2. **Loan Approval Prediction (Binary Classification):** Predict whether a loan application is likely to be **approved or denied** based on the applicant's financial and credit profile.

The project will also involve identifying the key factors influencing credit risk and loan approval, thereby providing the bank with **data-driven insights to support consistent, efficient, and risk-aware lending decisions.**


> The bank seeks to develop a machine learning-based credit risk assessment system that can evaluate loan applicants based on their demographic, employment, income, credit, and financial characteristics. The project aims to predict applicants' risk scores and loan approval outcomes, while identifying the key factors influencing these decisions. The resulting models can support the bank in making faster, more consistent, and data-driven lending decisions while managing potential default risk.

# DATA

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Loan.csv')
df

,ApplicationID,ApplicationDate,Gender,ResidenceType,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,...,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,YearsAtCurrentAddress,YearsWithCurrentBank,BankAccountAge,LoanApproved,RiskScore
0,APP000001,2018-01-01,Female,Urban,45,39948,617,Employed,Master,22,...,126928,0.199652,0.227590,419.805992,0.181077,9.4,12.9,14.4,0,49.0
1,APP000002,2018-01-02,Male,Urban,38,39709,628,Employed,Associate,15,...,43609,0.207045,0.201077,794.054238,0.389852,8.4,8.8,20.9,0,52.0
2,APP000003,2018-01-03,NaN,Urban,47,40724,570,Employed,Bachelor,26,...,5205,0.217627,0.212548,666.406688,0.462157,3.8,6.1,30.9,0,52.0
3,APP000004,2018-01-04,NaN,Urban,58,69084,545,Employed,High School,34,...,99452,0.300398,0.300911,1047.506980,0.313098,6.3,10.4,30.7,0,54.0
4,APP000005,2018-01-05,NaN,Rural,37,103264,594,Employed,Associate,17,...,227019,0.197184,0.175990,330.179140,0.070210,7.2,2.7,19.9,1,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,APP019996,2072-09-29,Female,Urban,44,30180,587,Employed,High School,19,...,55327,0.216021,0.195574,905.767712,0.627741,2.4,12.9,18.4,0,55.0
19996,APP019997,2072-09-30,Female,Urban,56,49246,567,Employed,Associate,33,...,64002,0.227318,0.199168,958.395633,0.334418,4.7,3.2,34.9,0,54.0
19997,APP019998,2072-10-01,Female,Urban,44,48958,645,Employed,Bachelor,20,...,103663,0.229533,0.226766,945.427454,0.357227,8.5,0.5,15.6,0,45.0
19998,APP019999,2072-10-02,NaN,Urban,60,41025,560,Employed,High School,36,...,10600,0.249760,0.264873,411.168284,0.408678,4.7,NaN,30.7,0,59.0
19999,APP020000,2072-10-03,Male,Urban,20,53227,574,Employed,Associate,0,...,41372,0.240055,0.242693,1049.830407,0.298006,1.8,1.3,0.5,0,59.0

### Basic Understanding Of Data

In [4]:
df.head()

,ApplicationID,ApplicationDate,Gender,ResidenceType,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,...,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,YearsAtCurrentAddress,YearsWithCurrentBank,BankAccountAge,LoanApproved,RiskScore
0,APP000001,2018-01-01,Female,Urban,45,39948,617,Employed,Master,22,...,126928,0.199652,0.227590,419.805992,0.181077,9.4,12.9,14.4,0,49.0
1,APP000002,2018-01-02,Male,Urban,38,39709,628,Employed,Associate,15,...,43609,0.207045,0.201077,794.054238,0.389852,8.4,8.8,20.9,0,52.0
2,APP000003,2018-01-03,NaN,Urban,47,40724,570,Employed,Bachelor,26,...,5205,0.217627,0.212548,666.406688,0.462157,3.8,6.1,30.9,0,52.0
3,APP000004,2018-01-04,NaN,Urban,58,69084,545,Employed,High School,34,...,99452,0.300398,0.300911,1047.506980,0.313098,6.3,10.4,30.7,0,54.0
4,APP000005,2018-01-05,NaN,Rural,37,103264,594,Employed,Associate,17,...,227019,0.197184,0.175990,330.179140,0.070210,7.2,2.7,19.9,1,36.0

In [5]:
df.tail()

,ApplicationID,ApplicationDate,Gender,ResidenceType,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,...,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,YearsAtCurrentAddress,YearsWithCurrentBank,BankAccountAge,LoanApproved,RiskScore
19995,APP019996,2072-09-29,Female,Urban,44,30180,587,Employed,High School,19,...,55327,0.216021,0.195574,905.767712,0.627741,2.4,12.9,18.4,0,55.0
19996,APP019997,2072-09-30,Female,Urban,56,49246,567,Employed,Associate,33,...,64002,0.227318,0.199168,958.395633,0.334418,4.7,3.2,34.9,0,54.0
19997,APP019998,2072-10-01,Female,Urban,44,48958,645,Employed,Bachelor,20,...,103663,0.229533,0.226766,945.427454,0.357227,8.5,0.5,15.6,0,45.0
19998,APP019999,2072-10-02,NaN,Urban,60,41025,560,Employed,High School,36,...,10600,0.249760,0.264873,411.168284,0.408678,4.7,NaN,30.7,0,59.0
19999,APP020000,2072-10-03,Male,Urban,20,53227,574,Employed,Associate,0,...,41372,0.240055,0.242693,1049.830407,0.298006,1.8,1.3,0.5,0,59.0

In [6]:
df.sample()

,ApplicationID,ApplicationDate,Gender,ResidenceType,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,...,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,YearsAtCurrentAddress,YearsWithCurrentBank,BankAccountAge,LoanApproved,RiskScore
14692,APP014693,2058-03-24,NaN,Urban,27,116887,492,Employed,Associate,3,...,5564,0.328478,0.262782,2091.663837,0.238042,5.5,6.4,12.0,0,61.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 42 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ApplicationID               20000 non-null  str
 1   ApplicationDate             20000 non-null  str
 2   Gender                      7476 non-null   str
 3   ResidenceType               17669 non-null  str
 4   Age                         20000 non-null  int64
 5   AnnualIncome                20000 non-null  int64
 6   CreditScore                 20000 non-null  int64
 7   EmploymentStatus            20000 non-null  str
 8   EducationLevel              20000 non-null  str
 9   Experience                  20000 non-null  int64
 10  LoanAmount                  20000 non-null  int64
 11  LoanDuration                20000 non-null  int64
 12  MaritalStatus               20000 non-null  str
 13  NumberOfDependents          20000 non-null  int64
 14  HomeOwnershipStatus         20000 non-null  str
 15  MonthlyDebtPayments         20000 non-null  int64
 16  CreditCardUtilizationRate   20000 non-null  float64
 17  NumberOfOpenCreditLines     20000 non-null  int64
 18  NumberOfCreditInquiries     20000 non-null  int64
 19  DebtToIncomeRatio           20000 non-null  float64
 20  BankruptcyHistory           20000 non-null  int64
 21  LoanPurpose                 20000 non-null  str
 22  PreviousLoanDefaults        20000 non-null  int64
 23  PaymentHistory              20000 non-null  int64
 24  LengthOfCreditHistory       20000 non-null  int64
 25  SavingsAccountBalance       20000 non-null  int64
 26  CheckingAccountBalance      20000 non-null  int64
 27  TotalAssets                 20000 non-null  int64
 28  TotalLiabilities            20000 non-null  int64
 29  MonthlyIncome               20000 non-null  float64
 30  UtilityBillsPaymentHistory  20000 non-null  float64
 31  JobTenure                   20000 non-null  int64
 32  NetWorth                    20000 non-null  int64
 33  BaseInterestRate            20000 non-null  float64
 34  InterestRate                20000 non-null  float64
 35  MonthlyLoanPayment          20000 non-null  float64
 36  TotalDebtToIncomeRatio      20000 non-null  float64
 37  YearsAtCurrentAddress       18443 non-null  float64
 38  YearsWithCurrentBank        18643 non-null  float64
 39  BankAccountAge              18142 non-null  float64
 40  LoanApproved                20000 non-null  int64
 41  RiskScore                   20000 non-null  float64
dtypes: float64(12), int64(21), str(9)
memory usage: 6.4 MB

In [8]:
df.describe()

,Age,AnnualIncome,CreditScore,Experience,LoanAmount,LoanDuration,NumberOfDependents,MonthlyDebtPayments,CreditCardUtilizationRate,NumberOfOpenCreditLines,...,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,YearsAtCurrentAddress,YearsWithCurrentBank,BankAccountAge,LoanApproved,RiskScore
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,18443.000000,18643.000000,18142.000000,20000.000000,20000.000000
mean,39.752600,59161.473550,571.612400,17.522750,24882.867800,54.057000,1.517300,454.292700,0.286381,3.023350,...,7.229432e+04,0.239124,0.239110,911.607052,0.402182,8.748647,6.002939,17.234787,0.239000,50.766780
std,11.622713,40350.845168,50.997358,11.316836,13427.421217,24.664857,1.386325,240.507609,0.159793,1.736161,...,1.179200e+05,0.035509,0.042205,674.583473,0.338924,5.859055,4.224339,10.781535,0.426483,7.778262
min,18.000000,15000.000000,343.000000,0.000000,3674.000000,12.000000,0.000000,50.000000,0.000974,0.000000,...,1.000000e+03,0.130101,0.113310,97.030193,0.016043,0.500000,0.500000,0.500000,0.000000,28.800000
25%,32.000000,31679.000000,540.000000,9.000000,15575.000000,36.000000,0.000000,286.000000,0.160794,2.000000,...,8.734750e+03,0.213889,0.209142,493.763700,0.179693,4.400000,2.900000,8.500000,0.000000,46.000000
50%,40.000000,48566.000000,578.000000,17.000000,21914.500000,48.000000,1.000000,402.000000,0.266673,3.000000,...,3.285550e+04,0.236157,0.235390,728.511452,0.302711,7.500000,5.000000,17.100000,0.000000,52.000000
75%,48.000000,74391.000000,609.000000,25.000000,30835.000000,72.000000,2.000000,564.000000,0.390634,4.000000,...,8.882550e+04,0.261533,0.265532,1112.770759,0.509214,11.700000,8.100000,25.700000,0.000000,56.000000
max,80.000000,485341.000000,712.000000,61.000000,184732.000000,120.000000,5.000000,2919.000000,0.917380,13.000000,...,2.603208e+06,0.405029,0.446787,10892.629520,4.647657,30.000000,25.000000,35.000000,1.000000,84.000000

In [10]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Length: 20000, dtype: bool

In [12]:
df.shape

(20000, 42)

In [17]:
df.columns

Index(['ApplicationID', 'ApplicationDate', 'Gender', 'ResidenceType', 'Age',
       'AnnualIncome', 'CreditScore', 'EmploymentStatus', 'EducationLevel',
       'Experience', 'LoanAmount', 'LoanDuration', 'MaritalStatus',
       'NumberOfDependents', 'HomeOwnershipStatus', 'MonthlyDebtPayments',
       'CreditCardUtilizationRate', 'NumberOfOpenCreditLines',
       'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory',
       'LoanPurpose', 'PreviousLoanDefaults', 'PaymentHistory',
       'LengthOfCreditHistory', 'SavingsAccountBalance',
       'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities',
       'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth',
       'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment',
       'TotalDebtToIncomeRatio', 'YearsAtCurrentAddress',
       'YearsWithCurrentBank', 'BankAccountAge', 'LoanApproved', 'RiskScore'],
      dtype='str')

In [23]:
df.isnull().sum()

ApplicationID                     0
ApplicationDate                   0
Gender                        12524
ResidenceType                  2331
Age                               0
AnnualIncome                      0
CreditScore                       0
EmploymentStatus                  0
EducationLevel                    0
Experience                        0
LoanAmount                        0
LoanDuration                      0
MaritalStatus                     0
NumberOfDependents                0
HomeOwnershipStatus               0
MonthlyDebtPayments               0
CreditCardUtilizationRate         0
NumberOfOpenCreditLines           0
NumberOfCreditInquiries           0
DebtToIncomeRatio                 0
BankruptcyHistory                 0
LoanPurpose                       0
PreviousLoanDefaults              0
PaymentHistory                    0
LengthOfCreditHistory             0
SavingsAccountBalance             0
CheckingAccountBalance            0
TotalAssets                       0
TotalLiabilities                  0
MonthlyIncome                     0
UtilityBillsPaymentHistory        0
JobTenure                         0
NetWorth                          0
BaseInterestRate                  0
InterestRate                      0
MonthlyLoanPayment                0
TotalDebtToIncomeRatio            0
YearsAtCurrentAddress          1557
YearsWithCurrentBank           1357
BankAccountAge                 1858
LoanApproved                      0
RiskScore                         0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [27]:
categorical_columns = df.select_dtypes(include=['object','string']).columns.tolist()
print("categorical columns:",categorical_columns)

categorical columns: ['ApplicationID', 'ApplicationDate', 'Gender', 'ResidenceType', 'EmploymentStatus', 'EducationLevel', 'MaritalStatus', 'HomeOwnershipStatus', 'LoanPurpose']

In [33]:
numerics = ['int16','int32','int64','float16','float16','float32','float64']
numerical_columns = df.select_dtypes(include=numerics).columns.tolist()

print("numerical columns:",numerical_columns)

numerical columns: ['Age', 'AnnualIncome', 'CreditScore', 'Experience', 'LoanAmount', 'LoanDuration', 'NumberOfDependents', 'MonthlyDebtPayments', 'CreditCardUtilizationRate', 'NumberOfOpenCreditLines', 'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory', 'PreviousLoanDefaults', 'PaymentHistory', 'LengthOfCreditHistory', 'SavingsAccountBalance', 'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities', 'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth', 'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment', 'TotalDebtToIncomeRatio', 'YearsAtCurrentAddress', 'YearsWithCurrentBank', 'BankAccountAge', 'LoanApproved', 'RiskScore']

## visualization

In [34]:
import matplotlib.pyplot as plt

In [35]:
import seaborn as sns